name: Stackable
version: '${version}'
main: net.hynse.stackable.Stackable
api-version: '1.21'
folia-supported: true
website: https://github.com/TrekkieEnderman/Stackable
description: A fork of the original Stackable by MidnightTale, made to be permission-based.
authors: [MidnightTale, TrekkieEndermom]
commands:
  stackablereload:
    description: Reloads the Stackable plugin configuration
    usage: /stackablereload
    permission: stackable.admin
  stackabletest:
    description: Test regex patterns against material names
    usage: /stackabletest <pattern> [material]
    permission: stackable.admin
permissions:
  stackable.admin:
    default: op
  stackable.reload:
    default: op
    children:
      stackable.admin: true
  stackable.enable:
    default: false
    description: "Allows usage of customized stack sizes"
